<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace Magento\ImportExport\Model\Import\Source;

/**
 * CSV import adapter
 */
class Product extends \Magento\ImportExport\Model\Import\Source\Csv
{
    public function current()
    {
        return parent::current(); // TODO: Change the autogenerated stub
    }
}
